### ISSUE TITLE
cloaked_search_tenant_not_found error encountered in kubernetes deployment

### ISSUE THREAD

**Issue by ghosh11** [IronCoreLabs/try-cloaked-search#30]
I am trying out a POC with cloaked-search and OpenSearch. I was able to test it out successfully with Docker. However, run into this error when testing in Kubernetes.

> $ sh query-cloaked-search.sh '+tenant_id.keyword:"tenant-1" AND title:Japan' | jq
{
  "root_cause": [
    {
      "type": "cloaked_search_tenant_not_found",
      "reason": "Tenant ID field: 'tenant_id', Error: No tenant ID detected."
    }
  ],
  "type": "cloaked_search_tenant_not_found",
  "reason": "Tenant ID field: 'tenant_id', Error: No tenant ID detected."
}

I have OpenSearch and cloaked-search running in the same Kubernetes cluster.
Encryption seems to be working fine.

> [opensearch@opensearch-cluster-master-0 ~]$ curl -s -G --data-urlencode 'q=+tenant_id.keyword:"tenant-1" AND title:Jeon' "localhost:9200/try_cloaked_search/_search"
{"took":2,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":1,"relation":"eq"},"max_score":5.3773093,"hits":[{"_index":"try_cloaked_search","_id":"4i4_0o0BQcOhW1UrC9c6
","_score":5.3773093,"_source":{"url":"https://en.wikipedia.org/wiki?curid=48687903","title":"Jeon Hye-jin (actress, born 1988)","_icl_p_body":"5D814141 C508A1B8 30F481DB BE08BEC2 D3A6D439 C7002FAC B6422D53 B77C070C 5FB2
2F90 230E4512 1A30D794 19E58ACB 263E7A15 2F10D52 A9EAA25C 26002A5A 7E80080F C4A662FF A72D230D 94BC5FD2 C9623E90 5D64C1CE 46BB342C C2FD41F3 5E2404DF 89C241D5 AB787BA2 E5486B21 6EBA0D16 98F74D9B A8614E80 F7079D30 44D332D 5
F9BA497 F6BB5BAB 11270D90 3C180931 88D54E22 EA55022E D4933FE5 B3A0946E 6B1BBA1E 5794CBA C95C28C0 C673081C DCEDBD04 7C74DD5B B3D658FE BFB26284 7EA981B7 DCE069CE BB66423A 701FB44A EBCDDEA0 6D82BC65 8D20E1DE A89FE967 50D28B
91 9FBD80 3F5AEB5C 54D587A4 9D44454E E21B7331 F2287E6F DD01AE17 9150F5C9 60E6D4EE 6B3587D7 69BE57BB 59C8EA8A FAA5C68B 3653C729 D1BB77A9 47311E7 EBE2A6C8 F4A9A2CB 9954C83E 2A394ADD 9B6CC15F 4D73628C A2164883 45CE8B8C E073
A373 8AA7E5A4 90BC28E9 FFB9F7FB 5056CAB1 50893B7 9C744690 345745D0 F175C7F1 71D12224 33433B94 EADD1B3B 5F1D66CD 9C443614 1BA3F060 31F8786A 1F014B16 59C5C1F 28C9662E 496DF0AE DC05C933 3602F920 754E2380 80859DB8 C04CE7C5 5
52D40D8 DA592338 DB4D293F 5B7E134E 3321D857 A2DA4FC0 3C966E1E 5A839A1A B43A8CDE CC7C747C E8C15B14 8F26E35D A9A48880 5E1BD80F BD43C7E0 D3475EDE 2E4838A4 A4E6FEB2 A0345161 68AF7AF 65CC421B 6515C635 20E914B5 7D874651 B62ACF
35 12A659B0 7B8345F2 CE3FC3CB 601D13CE C5C3C09E 7AE87A72 D1BD0511 7A74F8BD E079A370 9F6336BB 9ED85CAF 1A4519C4 24BAED10 3674FA94 37A9A5F0 C499FEA9 B6AB845A 16720E33 31FBFE6E 272247 CDF5F35F 62CB9C38 F7459F03 276BFB1E 44E
4D808 58A4EE53 92DC9CC2 50A2322C 2EEDF0E5 A4419B55 8475760C 3A1B491 2482A056 FFF0D8E5 54C13B18 FA092AA3 AE1D155B 52C6423 6DDF0EC3 BE0B6CEC 2F3038CF 30B95190 65168D73 236B93DD 240B894E 4CE3D1A0 7E11A71C A05A1AA0 91ECE8AC
5EF6C399 4B22BA51 E75C97D CFBC803E 237FE297 24C189A7","tenant_id":"tenant-1","_icl_p_summary":"4758A86E DF08F361 67B1311C A8DA839A 1B2D195C 956F9F4E 7B813221 E131C3C5 D92A7B80 3069D81A 1F36F4B0 B7951EEB F7AD7F6 9691C1B3
E164FB94 B536470 8ABBF829 20ABE1FD 2C6731E3 5420DFEE 10664D08 B4963854 11BBDEB3 C010EC5C 2E9981C8 71AF6DE2 7DCF33D1 FCDD1021 28572968 4E94F2C6 3B409978 5758CC51","_icl_encrypted_source":"BElST04AggokCiADv1/s41cZfkYvxoSHi
/gbCuopsR4m+R4K9N7LeipllRABEloSWBpWCgwRUAG/9IPYLaDQDSESMEoBhoEvGbRFUuuW8tSLRhZseolfFxiWt6ILkQQczQ+93B4YhT3SVBlR2a11rnejIRoUcHJpbWFyeS1rZXl+dGVuYW50LTHUXsMABV6uLIQJAQzUkUEInmNtPcqnNevmyshikqFp2/ZybHUrrcFNUT6HrfloEshPY3vLq
703ErfRPq7vRnwri8iqoDm7syIXIk15lFwIkoU4KswjCpUMj14M9vRy7HNo0pwTQsn8ely5u+epHip0Ac9Z/E0qVyd7+382N5/7xEs2rAr+wA6oo4izveuSndrDhZK+o5/zQ6LFNLDFDeYH3inrfF4lIxXCaYduj1uhZSWjZBAdSujMY7SrBy1GT+HrvUWkCFgnfCE+WLSftJBsJXMOXKuxRCpso
OB+2fcYdh6kUfnHnGcZ2Nf/eN8LcxmvgxZNLX5Bnk3T3XIknUcEyZDbHMl6bWYSlZIiMJAlejcOjf5rb5Hc0hKRkEAtVYvVn4Z2Ng8BO8bTU8USK2qu94DrCw6Uer2rUyz/c4GYO4tkmcMUX/rBLQ==","_icl_search_key_id":"primary-key"}}]}}

Below is the deploy.yml file that i have setup cloaked-search with. I tweaked this (added tenant_id_index_field: tenant_id & tenant_id_search_field: tenant_id.keyword) as I was having no success with the original one either.

```
search_service_url: "http://opensearch-cluster-master.default.svc.cluster.local:9200"

standalone_keys:
  - id: primary-key
    keypath: /secrets/cloaked-search/key1
    primary: true
indices:
  - name: try_cloaked_search
    tenant_id_index_field: tenant_id
    tenant_id_search_field: tenant_id.keyword
    fields:
      - name: body
        analyzer:
          tokenizer: default
          filters:
            - lowercase
            - terms
            - phrases
            - substring
      - name: summary
        analyzer:
          tokenizer: default
          filters:
            - lowercase
            - terms
            - phrases
            - substring
```

What could be the issue here? Is there any documentation that I can follow?
